services:
  - type: web
    name: code-converter
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: daphne backend.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: WEB_CONCURRENCY
        value: 2
